### ISSUE TITLE
`rapply(... , sqrt, how="replace")` not behaving as expected

### ISSUE THREAD

**Issue by RobinHankin** [JorisChau/rrapply#14]
Hi there, love the package but am having difficulty interpreting the documentation.  Below,  I would expect the result of `rrapply()` to be along the lines of "recursively apply the square root function to every element of `x` and preserve the list structure in the return value".  But: 

```
> x <- list(2,list(6),list(3,5))
> rrapply(x,sqrt,how="replace")
[[1]]
[1] 2

[[2]]
[[2]][[1]]
[1] 6


[[3]]
[[3]][[1]]
[1] 3

[[3]][[2]]
[1] 5
```

It appears that the square root function has not been applied, what is wrong with my understanding?

**Comment by JorisChau** [comment]
@RobinHankin: can I close this issue?

**Comment by RobinHankin** [comment]
Hi Joris, sorry for the late reply, yes of course you can close it.  I
guess my problem was a lack of close reading of the help page

Best wishes

Robin
--
Robin K. S. Hankin
Associate Professor, computational statistics
