### ISSUE TITLE
NA nodes not correctly merged when using `how = "unmelt"`

### ISSUE THREAD

**Issue by agricolamz** [JorisChau/rrapply#16]
Hi, thank you for the package! I wanted to report to you a strange behavior of `rrapply(how = "unmelt")` with `NA`. If you have an `NA` value in the dataframe to melt, it won't be merged with other paths without an `NA` value. For example this code

```r
library(rrapply)

data.frame(L1 = c("A", "A", "A", "B", "B", "C"),
           L2 = c("1", "1", NA, "2", "2", "3"),
           L3 = c("a", "a", "z", "b", "b", "c")) |> 
  rrapply(how = "unmelt") |> 
  str()
```
will produce this structure: 

```
List of 4
 $ A:List of 2
  ..$ k: chr "a"
  ..$ l: chr "a"
 $ A: chr "a" # That is what I'm talking about
 $ B:List of 2
  ..$ m: chr "b"
  ..$ n: chr "b"
 $ C:List of 1
  ..$ o: chr "c"
```

As you see, there is an additional node `$ A: chr "z" ` that is not merged with other As. Just for clarification I'd provide the structure that I'd expected:

```
List of 3
 $ A:List of 3
  ..$ k: chr "a"
  ..$ l: chr "a"
  ..$  : chr "a" # That is what I'm talking about
 $ B:List of 2
  ..$ m: chr "b"
  ..$ n: chr "b"
 $ C:List of 1
  ..$ o: chr "c"
```

I know, that I can easily replace all `NA` values with `""` and get my expectations. But I decided that it would make sense to report to you.

Cheers!

I'm using rrapply of version 1.2.7.

**Comment by JorisChau** [comment]
@agricolamz: thanks for reporting this, but I think this is the expected output. `how = "unmelt"` is supposed to be the inverse of `how = "melt"` and the example data.frame in indeed the output of `how = "melt"` for the first list structure (and not the second):

```r
library(rrapply)

lst1 <- list(A = list(`1` = "a", `1` = "a"), A = "z", B = list(`2` = "b", `2` = "b"), C = list(`3` = "c"))
(df1 <- rrapply(lst1, how = "melt"))
#>   L1   L2 value
#> 1  A    1     a
#> 2  A    1     a
#> 3  A <NA>     z
#> 4  B    2     b
#> 5  B    2     b
#> 6  C    3     c
newlst1 <- rrapply(df1, how = "unmelt")

identical(lst1, newlst1)
#> [1] TRUE
```

The second list structure is the result of `how = "melt"` with the `NA` value replaced by `""` (as you also mentioned does give the expected result). If I would modify `how = "unmelt"` to return the second list structure in both cases, there is no longer a way to reconstruct the first list structure.

```r
lst2 <- list(A = list(`1` = "a", `1` = "a", "z"), B = list(`2` = "b", `2` = "b"), C = list(`3` = "c"))
(df2 <- rrapply(lst2, how = "melt"))
#>   L1 L2 value
#> 1  A  1     a
#> 2  A  1     a
#> 3  A        z
#> 4  B  2     b
#> 5  B  2     b
#> 6  C  3     c
newlst2 <- rrapply(df2, how = "unmelt")

identical(lst2, newlst2)
#> [1] TRUE
```

Please let me know if you disagree or if you see another way this could work (without breaking existing behavior of `how = "unmelt"`).

**Comment by JorisChau** [comment]
Follow-up: there is indeed some ambiguity here, since the same data.frame can also be constructed with `how = "melt"` like this:

```r
lst <- list(A = list("a", "a", "z"), B = list(`2` = "b", `2` = "b"), C = list(`3` = "c"))
names(lst$A) <- c("1", "1", NA)
str(lst)
#> List of 3
#>  $ A:List of 3
#>   ..$ 1 : chr "a"
#>   ..$ 1 : chr "a"
#>   ..$ NA: chr "z"
#>  $ B:List of 2
#>   ..$ 2: chr "b"
#>   ..$ 2: chr "b"
#>  $ C:List of 1
#>   ..$ 3: chr "c"

rrapply(lst, how = "melt")
#>   L1   L2 value
#> 1  A    1     a
#> 2  A    1     a
#> 3  A <NA>     z
#> 4  B    2     b
#> 5  B    2     b
#> 6  C    3     c
```

In which case `how = "unmelt"` does not return the exact inverse of `how = "melt"`. However, I think this use-case is quite uncommon (in comparison to the use-case in the previous comment), and it requires quite some effort to construct a list with `NA` names by hand, e.g. this is not valid syntax:

```r
lst <- list(A = list(`1` = "a", `1` = "a", NA = "z"), B = list(`2` = "b", `2` = "b"), C = list(`3` = "c"))
#> Error: <text>:1:47: unexpected '='
#> 1: lst <- list(A = list(`1` = "a", `1` = "a", NA =
#>                                                   ^
```

**Comment by agricolamz** [comment]
Hi! I see your logic, and I agree that from your perspective (symmetry of `melt` - `unmelt`) the question is strange. I came up with this going from dataframe to list, so without this `unmelt` step in the workflow. So if the case doesn't show any problems in the internal logic of the package, I'm happy, since that leaves you with no work on it!
