### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by simonhtausch** [JorisChau/rrapply#3]
Do you plan to contribute rrapply to conda-forge? Would be great to have it there too.

**Comment by JorisChau** [comment]
I am not familiar with contributing R-packages to conda-forge myself, might look into it at some point

**Comment by simonhtausch** [comment]
I've packaged it myself a while ago, forgot to close this. Thanks anyway, here it is: https://anaconda.org/conda-forge/r-rrapply
