### ISSUE TITLE
Collapsing terminal elements in a nested list

### ISSUE THREAD

**Issue by dleopold** [JorisChau/rrapply#8]
I just discovered `rrapply` and it has resulted in a ~10x speedup for some of my daily data workflows. Thank you! There is one operation that I like to apply recursively to nested lists, but have not been able to figure out. It may not be possible, but perhaps I am overlooking some relevant `rrapply` functionality. Specifically, I would like to take a nested list and collapse the terminal 'nodes' while applying a function using the names of the terminal elements. For example, given this list

`example <- list( A = list( S = "hello" ), B  =  list( C = list( S = "world" ), D = list( N = "1234" ) ) )`

I would like to return:

`list( A = "hello", B = list( C = "world", D = 1234 ) )`

where terminal elements with the name "S" are returned as is but those with name "N" are returned using `as.numeric()`. I think I understand how to accomplish the latter part (using element names to apply a specific function), but I am having trouble figuring out if the first part (collapsing terminal nodes) is possible with `rrapply`. I should note that the terminal nodes in the nested lists will always have 1 element, so they can be collapsed. Here is an example of the type of thing I am trying to accomplish in a case where recursion is not needed:

```
> foo <- list(A=list(S="hello"), B=list(S="world"), C=list(N="1234"))
> lapply(foo, function(x){
+   if(names(x)=="S"){return(x[[1]])}
+   if(names(x)=="N"){return(as.numeric(x[[1]]))}
+ })
$A
[1] "hello"

$B
[1] "world"

$C
[1] 1234
```

**Comment by dleopold** [comment]
Looks like I gave up just a little too soon. Here is a solution:

```
> example <- list( A = list( S = "hello" ), B = list( C = list( S = "world" ), D = list( N = "1234" ) ) )
> rrapply::rrapply(
+   example,
+   classes = "list",
+   condition = \(x) length(x)==1L,
+   f = function(x) {
+     if(names(x)=="S"){return(x[[1]])}
+     if(names(x)=="N"){return(as.numeric(x[[1]]))}
+   }
+ )
$A
[1] "hello"

$B
$B$C
[1] "world"

$B$D
[1] 1234
```
FWIW - one reason that I got stuck on this problem is that an older version of the documentation is showing up first in my google search results. Once I realized this and read the current docs, the example under "Modifying list elements" was very clear. Thanks again for the package!

**Comment by JorisChau** [comment]
Thanks for the comment and reply! I guess slightly better would be expand the `condition` function a bit:

```{r}
rrapply::rrapply(
  example,
  classes = "list",
  condition = \(x) length(x) == 1 && !is.list(x[[1]]),
  f = \(x) if(names(x) == "N") as.numeric(x[[1]]) else x[[1]]
)
```
There could be length 1 lists that are not necessarily terminal nodes
